// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category = { id: string, name: string, type: string, 
/**
 * 分类级扫描目录，缺省时回退到顶层 scanRoot
 */
scanPath: string | null, 
/**
 * 手动归属：汇总目录下划入本分类的一级子目录名（按填写顺序展示）；
 * 为空表示目录初始为空，工具通过编辑卡片的「所属目录」手动分配
 */
dirs: Array<string>, 
/**
 * 排序权重：数值越大在侧边栏越靠前；同权重保持 menu.json 中的原有先后顺序。
 * 旧数据缺省为 0
 */
weight: number, };

/**
 * 用户导入的自定义背景图
 */
export type CustomBg = { 
/**
 * 图片绝对路径
 */
path: string, 
/**
 * 归属主题：light / dark
 */
theme: string, };

export type MenuConfig = { categories: Array<Category>, 
/**
 * 工具目录汇总根目录（CMD 类工具统一存放处）
 */
scanRoot: string | null, };

export type ThemeSettings = { 
/**
 * default（保持原样）/ light / dark
 */
mode: string, 
/**
 * 页面透明度 0 ~ 1.0
 */
opacity: number, 
/**
 * 弹窗背景不透明度 0 ~ 1.0（1.0 = 完全不透明）
 */
dialogOpacity: number, 
/**
 * 弹窗背景高斯模糊半径（px），0 = 不模糊
 */
dialogBlur: number, 
/**
 * 背景图："builtin:light-1" 或自定义图片绝对路径
 */
bg: string | null, customBgs: Array<CustomBg>, };

export type Tool = { id: string, type: string, title: string, path: string, docPath: string | null, icon: string | null, categoryId: string, available: boolean, 
/**
 * EXE 类工具的启动参数（如 pythonw.exe -c "..."）；CMD 类恒为 None
 */
args: string | null, 
/**
 * 副标题：工具用途描述；CMD 类恒为 None
 */
desc: string | null, 
/**
 * 以管理员身份启动（EXE 类）；CMD 类恒为 false
 */
admin: boolean, 
/**
 * 关闭脚本（.bat/.cmd）路径（EXE 类可选）；CMD 类恒为 None
 */
stopPath: string | null, 
/**
 * 关闭脚本是否独立以管理员身份运行（EXE 类可选）；与启动用 admin 互不影响
 */
stopAdmin: boolean, 
/**
 * 排序权重：数值越大在分类内越靠前；默认 0
 */
weight: number, };
